version: "3.9"

services:
  # frontend:
  #   build:
  #     context: ./app/frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${FORWARD_FRONTEND_PORT:-80}:8080"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   volumes:
  #     - ../frontend:/app
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    ports:
      - "${FORWARD_BACKEND_PORT:-81}:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WWWUSER: "${WWWUSER}"
    volumes:
      - "../backend:/var/www/html"
      - "./app/backend/saml:/var/www/saml"
    depends_on:
      - mysql
      - redis
      
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "mysql:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "redis:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

volumes:
  mysql:
  redis:
